// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vupyblqvmszzpyaddfda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1cHlibHF2bXN6enB5YWRkZmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NDI4NzQsImV4cCI6MjA3NTExODg3NH0.liE3k_zCrOBRmDunHGzwrKwWwwVMuCna_Du1cTmqUqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});